require: rubocop-rspec

Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 9

Metrics/AbcSize:
  Enabled: true
  Exclude:
    - db/migrate/*

Metrics/MethodLength:
  Enabled: true
  Max: 13
  Exclude:
    - db/migrate/*

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 9

Metrics/BlockLength:
  Enabled: true
  Exclude: 
    - spec/models/*
    - spec/controllers/**/*.rb
    - spec/features/**/*.rb
    - config/environments/*
    - db/schema.rb

RSpec/Capybara/FeatureMethods:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: true
  Max: 4

RSpec/ExampleLength:
  Enabled: true
  Max: 15
  Exclude: 
    - spec/features/**/*.rb
