Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 9
require: rubocop-rspec

Metrics/MethodLength:
  Enabled: true
  Max: 13

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 9

Metrics/BlockLength:
  Enabled: true
  Exclude: 
    - spec/models/*
    - spec/controllers/*
    - spec/features/answer/*
    - spec/features/question/*
    - config/environments/*
    - db/schema.rb

RSpec/Capybara/FeatureMethods:
  Enabled: false

RSpec/NestedGroups:
  Enabled: true
  Max: 4

RSpec/ExampleLength:
  Enabled: true
  Max: 15
