Style/Documentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 9

Metrics/MethodLength:
  Enabled: true
  Max: 13

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 9

Metrics/BlockLength:
  Enabled: true
  Exclude: 
    - spec/controllers/*
    - spec/features/answer/*
    - spec/features/question/*
    - config/environments/*
    - db/schema.rb
