default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username:
  password:
  host:

development:
  <<: *default
  database: qna_development

test:
  <<: *default
  database: qna_test
